# Generated by Django 5.1.1 on 2024-09-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
