# Generated by Django 5.1.1 on 2024-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
