# Generated by Django 5.1.1 on 2024-09-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('code', models.CharField(max_length=6)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='api.transaction')),
            ],
        ),
    ]
