# Generated by Django 5.1.1 on 2024-09-26 17:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='evidence',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
